name: Integración continua

on:
  push:
    branch: [ main ]
    paths: [ 'hangman-api/**']
  pull_request:
    branches: [ main ]
    paths: [ 'hangman-api/**']

jobs:
  buildAndTest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Build and Test
        working-directory: ./hangman-api
        run: |
          npm ci
          npm run build
          npm run test